# Generated by Django 3.2.6 on 2021-08-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_userprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
